### PR TITLE
CI: Add 3.0 and JRuby to the build matrix

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR only updates the CI matrix to the latest generally available Ruby versions.

Source for version numbers: https://github.com/rvm/rvm/blob/master/config/known

Did not include `3.0.0-preview2` **Update**: Added JRuby & 3.0, and allowed them to run with failures.

### CODE REVIEW

**Comment by epergo** [comment]
> Did not include 3.0.0-preview2

I think we could add ruby 3 now that it has released a new minor, and maybe we could add Jruby too because sinatra itself supports it

**Comment by olleolleolle** [comment]
@epergo Thought: Do you think it'd be alright to only keep version specifiers like "2.7" in the list?

**Comment by olleolleolle** [comment]
Cool! "3.0" runs, and shows several ArgumentError!

**Comment by olleolleolle** [comment]
JRuby fails on attempting to use redcarpet, which has a C extension. /home/travis/build/sinatra/mustermann/vendor/bundle/jruby/2.5.0/gems/redcarpet-3.5.1/ext/redcarpet

**Comment by epergo** [comment]
> @epergo Thought: Do you think it'd be alright to only keep version specifiers like "2.7" in the list?

Sounds good, Travis will download the latest minor version

As for Ruby 3 and jRuby errors, we can allow failures for them so we (aka someone with suppa powers 😄 ) can merge this `now()`

**Comment by zzak** [comment]
@olleolleolle Thanks for creating this!

I'm not sure about the jruby version, but I wonder if we can clean up and stop testing EoL'd versions of Ruby.

**Comment by olleolleolle** [comment]
@zzak I can drop every EOL'd version, right now.

**Comment by olleolleolle** [comment]
@zzak If you feel uneasy about adding a previously-not-there Ruby implementation, I can take that out of this PR, and move it to another Pull Request, which could be about "add JRuby to matrix AND make it pass green".

**Comment by zzak** [comment]
@olleolleolle I think it's fine but I just wasn't sure

**Review by zzak — APPROVED** [review]

**Pull request merged**
