### PR TITLE
v1.1.0

### PR DESCRIPTION
**Pull request by namusyaka**

### CODE REVIEW

**Comment by namusyaka** [comment]
For 2.7.0, https://github.com/lsegal/yard/pull/1296 needs to be merged.
For 2.6.5, I decided to use [the workaround](https://github.com/sinatra/mustermann/pull/100/commits/af585728712c46167fbd7c645e1863b64982092d) for the coverage decreasing issue.

**Comment by namusyaka** [comment]
..and, since we're having a breaking change on `Mustermann::Mapper`, I'll cut a new version which increases minor version.

**Comment by dentarg** [comment]
> ..and, since we're having a breaking change on `Mustermann::Mapper`, I'll cut a new version which increases minor version.

If there are breaking changes, shouldn't the major version be increased @namusyaka? [README](https://github.com/sinatra/mustermann/tree/db86e25f786c717dbe937d862a5ba0d35a58797b#release-history) states that Mustermann is following https://semver.org/

**Comment by namusyaka** [comment]
@dentarg No. It's just a bug fix essentially. I don't think we should cut a new major version upgrade because of the potential incompatibility caused by the bug fix around "ruby".
Even if we upgrade the major version, new ruby version introduce a new bug in the older versions such as 1.0.3.

I'm going to upgrade a major version when the public API is changed explicitly.

**Comment by deepj** [comment]
It's still not fixed yet. I get this warning with the lastest mustermann

```
~/.gem/ruby/2.7.0/gems/mustermann-1.1.0/lib/mustermann.rb:63: warning: The called method `new' is defined here
```

**Comment by namusyaka** [comment]
@deepj Looks like the warning is unrelated to the change/release.
If you worried about it, please file a new issue with a reproducible code.

**Pull request merged**
