### PR TITLE
Move the following gems to a single meta gem, called mustermann-contrib:

### PR DESCRIPTION
**Pull request by zzak**
* mustermann-cake
* mustermann-express
* mustermann-fileutils
* mustermann-flask
* mustermann-grape
* mustermann-pyramid
* mustermann-rails
* mustermann-shell
* mustermann-simple
* mustermann-strscan
* mustermann-uri-template
* mustermann-visualizer

We will no longer support mustermann-everything instead, this gem replaces it.

### CODE REVIEW

**Comment by namusyaka** [comment]
Why do you want to move gems to the single meta gem?
I don't think this is reasonable because this change makes require the all unnecessary code even if developer would like to use mustermann-simple.
I think all mustermann patterns should be separated as a gem.

**Comment by zzak** [comment]
@namusyaka After talking with @rkh about this, he suggested to combine the extra plugins to make release maintenance easier.

This change wouldn't be included until Mustermann 1.0.0, which I will cut once this is done.

The argument is most of these plugins are really small, and aren't autoloaded so the only would be disk space and network bandwidth when installing the gem. However, it's fair to assume most applications have tens if not hundreds of dependencies already, and this would actually cut down the number of packages required to download and install. As well, the real win here, is that I only have to cut 2 gems to release all of Mustermann and going forward is a much more sustainable strategy.

**Comment by zzak** [comment]
Also, I think this is OK to merge if everyone is happy and then I can cut a pre-release of Mustermann 1.0!

**Comment by namusyaka** [comment]
@zzak Hmm, makes sense.
Thanks for the thorough explanation.
I don't intend to deny the approach already if having obtained a consensus.

**Comment by zzak** [comment]
@namusyaka If there's any gem included here you'd like to take over (such as `mustermann-grape`), I'm happy to leave it out and you're free to maintain it separately.

**Pull request merged**
